repositoryUrl: https://github.com/dynamsoft-docs/label-recognition-docs-mobile/blob/main
repository: Dynamsoft-Docs/label-recognition-docs-mobile
docFullPath: https://www.dynamsoft.com/label-recognition/docs/mobile/
firstLevelUrl: /label-recognition/docs/mobile/
docHomePage: /label-recognition/docs/mobile/introduction/

enumerations: /label-recognition/docs/core/parameters/enum/
parameters-reference: /label-recognition/docs/core/parameters/reference/

android: /label-recognition/docs/mobile/programming/android/
android-api: /label-recognition/docs/mobile/programming/android/api-reference/
android-release-notes: /label-recognition/docs/mobile/programming/android/release-notes/

dlr_ios: /label-recognition/docs/mobile/programming/objectivec-swift/
dlr_ios_api: /label-recognition/docs/mobile/programming/objectivec-swift/api-reference/
dlr_ios_release_notes: /label-recognition/docs/mobile/programming/objectivec-swift/release-notes/

dcv_android_api: /capture-vision/docs/mobile/programming/android/api-reference/
dcv_ios_api: /capture-vision/docs/mobile/programming/ios/api-reference/
dcv_enumerations: /capture-vision/docs/core/enums/
dcv_parameter_reference: /capture-vision/docs/core/parameters/reference/

assets: /label-recognition/docs/mobile/assets/
edit_icon: /label-recognition/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /label-recognition/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /label-recognition/docs/mobile/assets/img-icon/icon-sad.png
dbr_icon: /label-recognition/docs/mobile/assets/img-icon/icon-dbr.svg
dwt_icon: /label-recognition/docs/mobile/assets/img-icon/icon-dwt.svg
dnt_icon: /label-recognition/docs/mobile/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/label-recognition/docs/mobile"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "programming-old/android"
    values:
      docRootName: "Label Recognizer Android Edition"
      docHomePage: "/label-recognition/docs/mobile/programming/android/"
  - scope:
      path: "programming-old/objectivec-swift"
    values:
      docRootName: "Label Recognizer iOS Edition"
      docHomePage: "/label-recognition/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "programming/android"
    values:
      docRootName: "Label Recognizer Android Edition"
      docHomePage: "/label-recognition/docs/mobile/programming/android/"
  - scope:
      path: "programming/objectivec-swift"
    values:
      docRootName: "Label Recognizer iOS Edition"
      docHomePage: "/label-recognition/docs/mobile/programming/objectivec-swift/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root

